FROM node:22-alpine AS base
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat python3 make g++ && \
    npm install -g pnpm
WORKDIR /usr/src/app

FROM base AS builder
RUN npm install -g turbo
COPY . .
RUN turbo prune web subgraph --docker --out-dir=./output && \
    cp apps/web/sampleData.ts ./output/full/apps/web/sampleData.ts && \
    cp apps/web/.env ./output/full/apps/web/.env

FROM base AS installer
COPY --from=builder /usr/src/app/output/full .
RUN pnpm install && \
    pnpm contracts:compile && \
    pnpm turbo build --filter=web

FROM base AS runner
USER node
COPY --from=installer --chown=node:node /usr/src/app/ .
CMD ["pnpm", "--filter=web", "start"]