/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RewardClaimerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimReward"
      | "claimableAmount"
      | "claimer"
      | "rewardToken"
      | "updateClaimAmount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "UpdatedClaimAmount"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimer",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateClaimAmount",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateClaimAmount",
    data: BytesLike
  ): Result;
}

export namespace UpdatedClaimAmountEvent {
  export type InputTuple = [
    token: AddressLike,
    repoId: BytesLike,
    claimableAmount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    repoId: string,
    claimableAmount: bigint
  ];
  export interface OutputObject {
    token: string;
    repoId: string;
    claimableAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardClaimer extends BaseContract {
  connect(runner?: ContractRunner | null): RewardClaimer;
  waitForDeployment(): Promise<this>;

  interface: RewardClaimerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimReward: TypedContractMethod<
    [_repoId: BytesLike, _PrId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimableAmount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  claimer: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  rewardToken: TypedContractMethod<[], [string], "view">;

  updateClaimAmount: TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _repoId: BytesLike,
      _claimableAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<
    [_repoId: BytesLike, _PrId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimer"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateClaimAmount"
  ): TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _repoId: BytesLike,
      _claimableAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "UpdatedClaimAmount"
  ): TypedContractEvent<
    UpdatedClaimAmountEvent.InputTuple,
    UpdatedClaimAmountEvent.OutputTuple,
    UpdatedClaimAmountEvent.OutputObject
  >;

  filters: {
    "UpdatedClaimAmount(address,bytes32,uint256)": TypedContractEvent<
      UpdatedClaimAmountEvent.InputTuple,
      UpdatedClaimAmountEvent.OutputTuple,
      UpdatedClaimAmountEvent.OutputObject
    >;
    UpdatedClaimAmount: TypedContractEvent<
      UpdatedClaimAmountEvent.InputTuple,
      UpdatedClaimAmountEvent.OutputTuple,
      UpdatedClaimAmountEvent.OutputObject
    >;
  };
}
