
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.13.0
 * Query Engine version: 361e86d0ea4987e9f53a565309b3eed797a6bcbd
 */
Prisma.prismaVersion = {
  client: "6.13.0",
  engine: "361e86d0ea4987e9f53a565309b3eed797a6bcbd"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  cuid: 'cuid',
  name: 'name',
  currency: 'currency',
  acctNumber: 'acctNumber',
  bankCode: 'bankCode',
  balance: 'balance',
  isInternal: 'isInternal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.AccountTransactionScalarFieldEnum = {
  cuid: 'cuid',
  accountId: 'accountId',
  reconDetails: 'reconDetails',
  status: 'status',
  type: 'type',
  pstdDate: 'pstdDate',
  txnCurrencyCode: 'txnCurrencyCode',
  description: 'description',
  txnCode: 'txnCode',
  debitAmount: 'debitAmount',
  creditAmount: 'creditAmount',
  balanceAmount: 'balanceAmount',
  chequeNumber: 'chequeNumber',
  txnAmount: 'txnAmount',
  txnDate: 'txnDate',
  txnId: 'txnId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.CategoryScalarFieldEnum = {
  cuid: 'cuid',
  name: 'name',
  group: 'group',
  isSystem: 'isSystem',
  meta: 'meta',
  extras: 'extras',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ProjectScalarFieldEnum = {
  cuid: 'cuid',
  name: 'name',
  departmentId: 'departmentId',
  owner: 'owner',
  meta: 'meta',
  extras: 'extras',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ProjectMemberScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  userId: 'userId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.IncomeScalarFieldEnum = {
  cuid: 'cuid',
  date: 'date',
  clientId: 'clientId',
  amount: 'amount',
  vat: 'vat',
  bankFees: 'bankFees',
  description: 'description',
  currency: 'currency',
  accountId: 'accountId',
  projectId: 'projectId',
  attachments: 'attachments',
  remarks: 'remarks',
  isVerified: 'isVerified',
  verificationDetails: 'verificationDetails',
  isReconciled: 'isReconciled',
  reconDetails: 'reconDetails',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  cuid: 'cuid',
  date: 'date',
  description: 'description',
  departmentId: 'departmentId',
  categoryId: 'categoryId',
  amount: 'amount',
  currency: 'currency',
  vatAmount: 'vatAmount',
  bankTransferFees: 'bankTransferFees',
  projectId: 'projectId',
  invoiceType: 'invoiceType',
  accountId: 'accountId',
  attachments: 'attachments',
  source: 'source',
  remarks: 'remarks',
  extras: 'extras',
  isReconciled: 'isReconciled',
  reconDetails: 'reconDetails',
  isVerified: 'isVerified',
  verificationDetails: 'verificationDetails',
  receiptId: 'receiptId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.SalaryDraftScalarFieldEnum = {
  cuid: 'cuid',
  month: 'month',
  year: 'year',
  status: 'status',
  numberOfEmployee: 'numberOfEmployee',
  numberOfEmployeePaid: 'numberOfEmployeePaid',
  totalAmountDue: 'totalAmountDue',
  totalAmountPaid: 'totalAmountPaid',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.SalaryScalarFieldEnum = {
  cuid: 'cuid',
  employeeId: 'employeeId',
  salaryDraftId: 'salaryDraftId',
  amountDue: 'amountDue',
  amountPaid: 'amountPaid',
  isPartial: 'isPartial',
  expenseId: 'expenseId',
  status: 'status',
  isArchived: 'isArchived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.ClientScalarFieldEnum = {
  cuid: 'cuid',
  clientId: 'clientId',
  name: 'name',
  country: 'country',
  extras: 'extras',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  cuid: 'cuid',
  date: 'date',
  description: 'description',
  amount: 'amount',
  categoryId: 'categoryId',
  projectId: 'projectId',
  userId: 'userId',
  currency: 'currency',
  invoiceType: 'invoiceType',
  vatAmount: 'vatAmount',
  bankTransferFees: 'bankTransferFees',
  status: 'status',
  attachments: 'attachments',
  approvalChallenge: 'approvalChallenge',
  approvalDetails: 'approvalDetails',
  reimburseDetails: 'reimburseDetails',
  extras: 'extras',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  cuid: 'cuid',
  name: 'name',
  group: 'group',
  owner: 'owner',
  meta: 'meta',
  extras: 'extras',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.UserDetailsScalarFieldEnum = {
  cuid: 'cuid',
  name: 'name',
  departmentId: 'departmentId',
  salary: 'salary',
  userType: 'userType',
  managerId: 'managerId',
  isApproved: 'isApproved',
  extras: 'extras',
  timeoffAllowance: 'timeoffAllowance',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  cuid: 'cuid',
  gender: 'gender',
  email: 'email',
  phone: 'phone',
  wallet: 'wallet',
  notes: 'notes',
  sessionId: 'sessionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.RoleScalarFieldEnum = {
  cuid: 'cuid',
  name: 'name',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.PermissionScalarFieldEnum = {
  cuid: 'cuid',
  roleId: 'roleId',
  action: 'action',
  subject: 'subject',
  inverted: 'inverted',
  conditions: 'conditions',
  reason: 'reason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  roleId: 'roleId',
  expiry: 'expiry',
  createdAt: 'createdAt',
  createdBy: 'createdBy'
};

exports.Prisma.AuthScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  service: 'service',
  serviceId: 'serviceId',
  details: 'details',
  challenge: 'challenge',
  falseAttempts: 'falseAttempts',
  isLocked: 'isLocked',
  lockedOnAt: 'lockedOnAt',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.AuthSessionScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  sessionId: 'sessionId',
  authId: 'authId',
  ip: 'ip',
  details: 'details',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.SettingScalarFieldEnum = {
  name: 'name',
  value: 'value',
  dataType: 'dataType',
  requiredFields: 'requiredFields',
  isReadOnly: 'isReadOnly',
  isPrivate: 'isPrivate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.HolidayScalarFieldEnum = {
  cuid: 'cuid',
  date: 'date',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.TimeOffRequestScalarFieldEnum = {
  cuid: 'cuid',
  userId: 'userId',
  type: 'type',
  startDate: 'startDate',
  endDate: 'endDate',
  daysDetails: 'daysDetails',
  totalDays: 'totalDays',
  status: 'status',
  description: 'description',
  extras: 'extras',
  attachments: 'attachments',
  isPaid: 'isPaid',
  approvalDetails: 'approvalDetails',
  approvalChallenge: 'approvalChallenge',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy'
};

exports.Prisma.TimeOffScalarFieldEnum = {
  id: 'id',
  timeOffId: 'timeOffId',
  userId: 'userId',
  date: 'date',
  type: 'type',
  duration: 'duration',
  isPaid: 'isPaid'
};

exports.Prisma.VatPurchaseScalarFieldEnum = {
  cuid: 'cuid',
  details: 'details',
  date: 'date',
  invoiceAmount: 'invoiceAmount',
  vatAmount: 'vatAmount',
  status: 'status',
  source: 'source',
  meta: 'meta',
  vatFilingCuid: 'vatFilingCuid'
};

exports.Prisma.VatSaleScalarFieldEnum = {
  cuid: 'cuid',
  details: 'details',
  date: 'date',
  invoiceAmount: 'invoiceAmount',
  vatAmount: 'vatAmount',
  status: 'status',
  source: 'source',
  meta: 'meta',
  vatFilingCuid: 'vatFilingCuid'
};

exports.Prisma.VatFilingScalarFieldEnum = {
  cuid: 'cuid',
  month: 'month',
  fiscalYear: 'fiscalYear',
  startDate: 'startDate',
  endDate: 'endDate',
  amount: 'amount',
  isFiled: 'isFiled',
  isClosed: 'isClosed',
  details: 'details',
  filedDate: 'filedDate'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.AccountTxnStatus = exports.$Enums.AccountTxnStatus = {
  UNRECONCILED: 'UNRECONCILED',
  RECONCILED: 'RECONCILED',
  DISCARDED: 'DISCARDED'
};

exports.AccountTxnType = exports.$Enums.AccountTxnType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.ProjectMemberRole = exports.$Enums.ProjectMemberRole = {
  OWNER: 'OWNER',
  MEMBER: 'MEMBER'
};

exports.Currency = exports.$Enums.Currency = {
  NPR: 'NPR',
  USD: 'USD',
  GBP: 'GBP',
  EUR: 'EUR',
  USDC: 'USDC'
};

exports.InvoiceType = exports.$Enums.InvoiceType = {
  VAT: 'VAT',
  PAN: 'PAN',
  ESTIMATE: 'ESTIMATE',
  BANK_TRANSFER: 'BANK_TRANSFER',
  VOUCHER: 'VOUCHER'
};

exports.DraftStatus = exports.$Enums.DraftStatus = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE'
};

exports.SalaryStatus = exports.$Enums.SalaryStatus = {
  PAID: 'PAID',
  PARTIAL: 'PARTIAL',
  UNPAID: 'UNPAID'
};

exports.InvoiceStatusType = exports.$Enums.InvoiceStatusType = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REIMBURSED: 'REIMBURSED'
};

exports.UserType = exports.$Enums.UserType = {
  EMPLOYEE: 'EMPLOYEE',
  VOLUNTEER: 'VOLUNTEER',
  CONTRACTOR: 'CONTRACTOR',
  INTERN: 'INTERN'
};

exports.Gender = exports.$Enums.Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
  UNKNOWN: 'UNKNOWN'
};

exports.Service = exports.$Enums.Service = {
  API: 'API',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  WALLET: 'WALLET',
  GOOGLE: 'GOOGLE',
  APPLE: 'APPLE',
  FACEBOOK: 'FACEBOOK',
  TWITTER: 'TWITTER',
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN'
};

exports.SettingDataType = exports.$Enums.SettingDataType = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  OBJECT: 'OBJECT'
};

exports.TimeOffType = exports.$Enums.TimeOffType = {
  VACATION: 'VACATION',
  SICK: 'SICK',
  PERSONAL: 'PERSONAL',
  UNPAID: 'UNPAID',
  MATERNITY: 'MATERNITY',
  PATERNITY: 'PATERNITY',
  BEREAVEMENT: 'BEREAVEMENT',
  COMPASSIONATE: 'COMPASSIONATE',
  OTHER: 'OTHER'
};

exports.TimeOffStatus = exports.$Enums.TimeOffStatus = {
  PENDING: 'PENDING',
  HR_APPROVED: 'HR_APPROVED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

exports.TimeOffDuration = exports.$Enums.TimeOffDuration = {
  FULL_DAY: 'FULL_DAY',
  FIRST_HALF: 'FIRST_HALF',
  SECOND_HALF: 'SECOND_HALF'
};

exports.VatStatus = exports.$Enums.VatStatus = {
  UNCLAIMED: 'UNCLAIMED',
  CLAIMED: 'CLAIMED',
  DELAYED_CLAIM: 'DELAYED_CLAIM',
  IGNORED: 'IGNORED'
};

exports.Prisma.ModelName = {
  Account: 'Account',
  AccountTransaction: 'AccountTransaction',
  Category: 'Category',
  Project: 'Project',
  ProjectMember: 'ProjectMember',
  Income: 'Income',
  Expense: 'Expense',
  SalaryDraft: 'SalaryDraft',
  Salary: 'Salary',
  Client: 'Client',
  Invoice: 'Invoice',
  Department: 'Department',
  UserDetails: 'UserDetails',
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  UserRole: 'UserRole',
  Auth: 'Auth',
  AuthSession: 'AuthSession',
  Setting: 'Setting',
  Holiday: 'Holiday',
  TimeOffRequest: 'TimeOffRequest',
  TimeOff: 'TimeOff',
  VatPurchase: 'VatPurchase',
  VatSale: 'VatSale',
  VatFiling: 'VatFiling'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
