type AppCreated @entity(immutable: true) {
  id: Bytes!
  appId: Bytes! # bytes32
  account: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  appId: Bytes! # bytes32
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type RoleGranted @entity(immutable: true) {
  id: Bytes!
  appId: Bytes! # bytes32
  role: Bytes! # bytes32
  account: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type RoleRevoked @entity(immutable: true) {
  id: Bytes!
  appId: Bytes! # bytes32
  role: Bytes! # bytes32
  account: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
type Approval @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  spender: Bytes! # address
  value: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Transfer @entity(immutable: true) {
  id: Bytes!
  from: Bytes! # address
  to: Bytes! # address
  value: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
type EntityTaskManagerCreated @entity {
  id: Bytes!
  entityTaskManager: Bytes! # address
  aclAddress: Bytes! # address
  _appId: Bytes! # bytes32
  _name: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  tasks: [TaskCreated!] @derivedFrom(field: "entityTaskManager")
  mintedTokens: [TokenMinted!] @derivedFrom(field: "entityTaskManager") 
  totalTokenBalance: BigInt! # Changed from optional to required
  allocatedToTasks: BigInt! # Changed from optional to required
  distributed: BigInt! # Changed from optional to required
  remainingBalance: BigInt! # Changed from optional to required
}

type TokenMinted @entity(immutable: true) {
  id: Bytes!
  entityTaskManager: EntityTaskManagerCreated! 
  tokenAddress: Bytes!
  amount: BigInt! 
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}


type PINGED @entity(immutable: true) {
  id: Bytes!
  sender: Bytes! # address
  timestamp: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ParticiantApplied @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  participant: Bytes! # address
  status: String # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  taskDetail: TaskDetail 
}

type TaskAccepted @entity(immutable: true) {
  id: Bytes!
  participant: Bytes! # address
  internal_id: Bytes! # bytes32
  blockNumber: BigInt!
  status: String # string
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  taskDetail: TaskDetail
}

type TaskApproved @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  approver: Bytes! # address
  status: String # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  taskDetail: TaskDetail
}

type TaskCompleted @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  participant: Bytes! # address
  blockNumber: BigInt!
  status: String # string
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  taskDetail: TaskDetail
}

type TaskCreated @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  createdBy: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  entityTaskManager: EntityTaskManagerCreated # Relationship to EntityTaskManagerCreated
  taskDetail: TaskDetail 
}

type TaskDetail @entity(immutable: false) {
  id: Bytes! # Task ID (e.g., detailsUrl)
  detailsUrl: String! # URL to the task details
  rewardToken: Bytes! # Address of the reward token
  rewardAmount: BigInt! # Amount of the reward
  maxParticipants: BigInt! # Maximum number of participants
  expiryDate: BigInt! # Expiry date of the task
  owner: Bytes! # Address of the task owner
  isActive: Boolean! # Whether the task is active
  allowedWallets: [Bytes!] # List of allowed wallets
  task: TaskCreated


}

type ParticipantTaskStatus @entity(immutable: false) {
  id: Bytes! 
  participant: Bytes! 
  taskId: Bytes! 
  status: String! 
  lastUpdatedBlock: BigInt! 
  lastUpdatedTimestamp: BigInt!
  taskDetail: TaskDetail
  entityTaskManager: EntityTaskManagerCreated
}

type TaskIdMapping @entity {
  id: Bytes! # internal_id (event.params.id)
  taskCreated: TaskCreated!
}

