/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAccessManagerV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "isAdmin"
      | "isMinter"
      | "isProjectManager"
      | "updateAdmin"
      | "updateMinter"
      | "updateProjectManager"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMinter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAdmin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectManager",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMinter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isProjectManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectManager",
    data: BytesLike
  ): Result;
}

export interface IAccessManagerV1 extends BaseContract {
  connect(runner?: ContractRunner | null): IAccessManagerV1;
  waitForDeployment(): Promise<this>;

  interface: IAccessManagerV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isAdmin: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isMinter: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isProjectManager: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  updateAdmin: TypedContractMethod<
    [_address: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  updateMinter: TypedContractMethod<
    [_address: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  updateProjectManager: TypedContractMethod<
    [_address: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMinter"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectManager"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateAdmin"
  ): TypedContractMethod<
    [_address: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMinter"
  ): TypedContractMethod<
    [_address: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProjectManager"
  ): TypedContractMethod<
    [_address: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
