/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IEntityTaskManager {
  export type TaskStruct = {
    detailsUrl: string;
    rewardToken: AddressLike;
    rewardAmount: BigNumberish;
    allowedWallets: AddressLike[];
    maxParticipants: BigNumberish;
    expiryDate: BigNumberish;
    owner: AddressLike;
    isActive: boolean;
  };

  export type TaskStructOutput = [
    detailsUrl: string,
    rewardToken: string,
    rewardAmount: bigint,
    allowedWallets: string[],
    maxParticipants: bigint,
    expiryDate: bigint,
    owner: string,
    isActive: boolean
  ] & {
    detailsUrl: string;
    rewardToken: string;
    rewardAmount: bigint;
    allowedWallets: string[];
    maxParticipants: bigint;
    expiryDate: bigint;
    owner: string;
    isActive: boolean;
  };
}

export interface IEntityTaskManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptParticipant"
      | "completeTask"
      | "createTask"
      | "name"
      | "participate"
      | "taskAssignments"
      | "verifyCompletion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ParticiantApplied"
      | "TaskAccepted"
      | "TaskApproved"
      | "TaskCompleted"
      | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptParticipant",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [IEntityTaskManager.TaskStruct]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "participate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "taskAssignments",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCompletion",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskAssignments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCompletion",
    data: BytesLike
  ): Result;
}

export namespace ParticiantAppliedEvent {
  export type InputTuple = [id: string, participant: AddressLike];
  export type OutputTuple = [id: string, participant: string];
  export interface OutputObject {
    id: string;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAcceptedEvent {
  export type InputTuple = [id: string];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskApprovedEvent {
  export type InputTuple = [id: string, approver: AddressLike];
  export type OutputTuple = [id: string, approver: string];
  export interface OutputObject {
    id: string;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [id: string, participant: AddressLike];
  export type OutputTuple = [id: string, participant: string];
  export interface OutputObject {
    id: string;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [id: string, createdBy: AddressLike];
  export type OutputTuple = [id: string, createdBy: string];
  export interface OutputObject {
    id: string;
    createdBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEntityTaskManager extends BaseContract {
  connect(runner?: ContractRunner | null): IEntityTaskManager;
  waitForDeployment(): Promise<this>;

  interface: IEntityTaskManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptParticipant: TypedContractMethod<
    [taskId: string, participant: AddressLike],
    [void],
    "nonpayable"
  >;

  completeTask: TypedContractMethod<[taskId: string], [void], "nonpayable">;

  createTask: TypedContractMethod<
    [task: IEntityTaskManager.TaskStruct],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  participate: TypedContractMethod<[taskId: string], [void], "nonpayable">;

  taskAssignments: TypedContractMethod<
    [taskId: string, participant: AddressLike],
    [bigint],
    "view"
  >;

  verifyCompletion: TypedContractMethod<[taskId: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptParticipant"
  ): TypedContractMethod<
    [taskId: string, participant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<[taskId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [task: IEntityTaskManager.TaskStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participate"
  ): TypedContractMethod<[taskId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "taskAssignments"
  ): TypedContractMethod<
    [taskId: string, participant: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyCompletion"
  ): TypedContractMethod<[taskId: string], [void], "nonpayable">;

  getEvent(
    key: "ParticiantApplied"
  ): TypedContractEvent<
    ParticiantAppliedEvent.InputTuple,
    ParticiantAppliedEvent.OutputTuple,
    ParticiantAppliedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAccepted"
  ): TypedContractEvent<
    TaskAcceptedEvent.InputTuple,
    TaskAcceptedEvent.OutputTuple,
    TaskAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TaskApproved"
  ): TypedContractEvent<
    TaskApprovedEvent.InputTuple,
    TaskApprovedEvent.OutputTuple,
    TaskApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "ParticiantApplied(string,address)": TypedContractEvent<
      ParticiantAppliedEvent.InputTuple,
      ParticiantAppliedEvent.OutputTuple,
      ParticiantAppliedEvent.OutputObject
    >;
    ParticiantApplied: TypedContractEvent<
      ParticiantAppliedEvent.InputTuple,
      ParticiantAppliedEvent.OutputTuple,
      ParticiantAppliedEvent.OutputObject
    >;

    "TaskAccepted(string)": TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;
    TaskAccepted: TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;

    "TaskApproved(string,address)": TypedContractEvent<
      TaskApprovedEvent.InputTuple,
      TaskApprovedEvent.OutputTuple,
      TaskApprovedEvent.OutputObject
    >;
    TaskApproved: TypedContractEvent<
      TaskApprovedEvent.InputTuple,
      TaskApprovedEvent.OutputTuple,
      TaskApprovedEvent.OutputObject
    >;

    "TaskCompleted(string,address)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(string,address)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
