/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAppRegistry } from "./IAppRegistry";
export type { IRewardManagement } from "./IRewardManagement";
export type { IRewardToken } from "./IRewardToken";
