/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccessManagerV1 } from "./IAccessManagerV1";
export type { IAccessManagerV2 } from "./IAccessManagerV2";
export type { IEntityTaskManager } from "./IEntityTaskManager";
export type { IRewardToken } from "./IRewardToken";
