/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAppRegistry__factory } from "./IAppRegistry__factory";
export { IRewardManagement__factory } from "./IRewardManagement__factory";
export { IRewardToken__factory } from "./IRewardToken__factory";
