/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccessManager__factory } from "./AccessManager__factory";
export { IAccessManaged__factory } from "./IAccessManaged__factory";
export { IAccessManager__factory } from "./IAccessManager__factory";
