/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface EntityTaskManagerFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createEntityTaskManager"
      | "deployedContracts"
      | "getDeployedContracts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createEntityTaskManager",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedContracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedContracts",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createEntityTaskManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedContracts",
    data: BytesLike
  ): Result;
}

export interface EntityTaskManagerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EntityTaskManagerFactory;
  waitForDeployment(): Promise<this>;

  interface: EntityTaskManagerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createEntityTaskManager: TypedContractMethod<
    [aclAddress: AddressLike, _appId: BytesLike],
    [void],
    "nonpayable"
  >;

  deployedContracts: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  getDeployedContracts: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createEntityTaskManager"
  ): TypedContractMethod<
    [aclAddress: AddressLike, _appId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedContracts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDeployedContracts"
  ): TypedContractMethod<[], [string[]], "view">;

  filters: {};
}
