name: Stage CI/CD
on:
  push:
    branches:
      - "stage"
  pull_request:
    branches:
      - "stage"
  workflow_dispatch:

env:
  CI: false
  MANIFEST_FILE: "K8s-Manifest/Rumsan/VirtuPerks/argo-rollout.yaml"


jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get short SHA and short Run ID
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "run_id_short=${GITHUB_RUN_ID: -4}" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              github/data/general/docker/rumsan username | DOCKERHUB_USERNAME ;
              github/data/general/docker/rumsan password | DOCKERHUB_TOKEN ;
              github/data/rumsan/virtuperks/web/sampleData stage | SAMPLE_DATA ;
              github/data/rumsan/virtuperks/web/env stage | ENV_STAGE ;

      - name: create environment file
        run: |
          tee ./apps/web/.env <<<"$ENV_STAGE"
          tee ./apps/web/sampleData.ts <<<"$SAMPLE_DATA"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Events-App Image
      - name: build && push events-app
        id: build-push-events-app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.web
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            rumsan/virtuperks-web:stage
            rumsan/virtuperks-web:stage-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      run_id_short: ${{ steps.vars.outputs.run_id_short }}

  update-manifest:
    name: Update Kubernetes Manifest
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/Stage-Manifest repo | MANIFEST_REPO ;
            github/data/general/Stage-Manifest ssh-key | SSH_KEY ;


      # Checkout the manifest repository using SSH
      - name: Checkout Stage Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO }}
          ssh-key: ${{ env.SSH_KEY }}

      # Update the image tag in the manifest
      - name: Update Image Tag in Manifest
        run: |
          sed -i "s|image: rumsan/virtuperks-web:.*|image: rumsan/virtuperks-web:stage-${{ needs.deploy.outputs.sha_short }}-${{ needs.deploy.outputs.run_id_short }}|" ${{ env.MANIFEST_FILE }}

      # Commit and push changes using SSH
      - name: Commit and Push Changes
        run: |
          git config user.name "sandab-rumsan"
          git config user.email "sandab@rumsan.net"
          git add ${{ env.MANIFEST_FILE }}
          git commit -m "runner: Update virtual-app image tag to stage-${{ needs.deploy.outputs.sha_short }}-${{ needs.deploy.outputs.run_id_short }}"
          git push origin main  