/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessManager } from "./AccessManager";
export type { IAccessManaged } from "./IAccessManaged";
export type { IAccessManager } from "./IAccessManager";
